import React, { useState } from "react";
import styles from "./FraudDetection.module.css";
import { 
  Shield, 
  Globe, 
  Search, 
  Bot, 
  Fingerprint, 
  TrendingUp, 
  MousePointer, 
  Monitor, 
  Smartphone, 
  BarChart, 
  Clock, 
  Target, 
  AlertTriangle,
  CheckCircle,
  XCircle
} from "lucide-react";

const FraudDetection = () => {
  const [selectedPlan, setSelectedPlan] = useState(null);
  const [isModalOpen, setIsModalOpen] = useState(false);

  const fraudDetectionFeatures = [
    {
      icon: <Globe className={styles.featureIcon} />,
      title: "IP Reputation Checks",
      description: "IP addresses are checked against global blacklists and databases to determine whether they have a negative reputation. This helps to prevent fraud and other malicious activities from suspicious IPs."
    },
    {
      icon: <Search className={styles.featureIcon} />,
      title: "Proxy / VPN Detection",
      description: "Identifies if a user is masking their identity by using a proxy or VPN. This is important for preventing access from potentially fraudulent or compromised sources."
    },
    {
      icon: <Bot className={styles.featureIcon} />,
      title: "Bot / Non-Human Detection",
      description: "Detects whether the traffic is generated by automated bots rather than real users. This helps in distinguishing genuine user actions from fraudulent activities."
    },
    {
      icon: <Fingerprint className={styles.featureIcon} />,
      title: "Device Fingerprinting",
      description: "Collects unique information from a device's configuration, such as browser type, screen resolution, and hardware properties, to create a unique fingerprint."
    },
    {
      icon: <TrendingUp className={styles.featureIcon} />,
      title: "Conversion Rate Analysis",
      description: "Monitors the percentage of users who take a desired action, such as completing a purchase or installing an app. Ensures conversion rates are within expected norms."
    },
    {
      icon: <MousePointer className={styles.featureIcon} />,
      title: "Click Pattern Analysis",
      description: "Analyzes user click patterns to identify unnatural behavior that may indicate fraudulent activity or bot traffic."
    },
    {
      icon: <Monitor className={styles.featureIcon} />,
      title: "Device & Browser Analysis",
      description: "Examines device and browser characteristics to detect inconsistencies that may suggest fraudulent installations or activities."
    },
    {
      icon: <Smartphone className={styles.featureIcon} />,
      title: "Mobile Device Verification",
      description: "Verifies the authenticity of mobile devices and detects emulators or modified devices used for fraudulent purposes."
    }
  ];

  const securityMetrics = [
    {
      icon: <CheckCircle className={styles.metricIcon} />,
      title: "99.8% Accuracy",
      description: "Our fraud detection system achieves 99.8% accuracy in identifying legitimate vs fraudulent traffic"
    },
    {
      icon: <BarChart className={styles.metricIcon} />,
      title: "Real-Time Processing",
      description: "All traffic is analyzed in real-time with毫秒级 response times"
    },
    {
      icon: <Clock className={styles.metricIcon} />,
      title: "24/7 Monitoring",
      description: "Continuous monitoring and protection around the clock"
    },
    {
      icon: <Target className={styles.metricIcon} />,
      title: "Targeted Protection",
      description: "Precise fraud prevention without affecting legitimate user traffic"
    }
  ];

  const handleGetStarted = (planName) => {
    setSelectedPlan(planName);
    setIsModalOpen(true);
  };

  const handleCloseModal = () => {
    setIsModalOpen(false);
    setSelectedPlan(null);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    alert(`Thank you for your interest in the ${selectedPlan} plan! Our team will contact you shortly.`);
    handleCloseModal();
  };

  return (
    <div>
      <div className={styles.container}>
        <div className={styles.wrapper}>
          <div className={styles.pageHeader}>
            <div className={styles.iconWrapper}>
              <Shield className={styles.shieldIcon} />
            </div>
            <h1 className={styles.mainTitle}>Advanced Fraud Detection</h1>
            <p className={styles.subtitle}>
              Protect your campaigns with our cutting-edge fraud detection technology that identifies and prevents 
              fraudulent activity in real-time while preserving legitimate user traffic.
            </p>
          </div>

          <div className={styles.mainContent}>
            <div className={styles.contentLeft}>
              <div className={styles.textSection}>
                <h2 className={styles.sectionTitle}>Comprehensive Fraud Prevention</h2>
                <p className={styles.sectionText}>
                  Our advanced fraud detection system employs multiple layers of protection to ensure your campaigns 
                  are safeguarded against malicious activity. With real-time monitoring and machine learning algorithms, 
                  we can identify and block fraudulent traffic while allowing legitimate users to engage with your content.
                </p>
                <p className={styles.sectionText}>
                  Our technology continuously evolves to stay ahead of emerging fraud tactics, providing you with 
                  peace of mind and protecting your investment in user acquisition campaigns.
                </p>
                
                <div className={styles.featuresList}>
                  <h3 className={styles.featuresTitle}>Key Features:</h3>
                  <ul className={styles.features}>
                    {fraudDetectionFeatures.slice(0, 4).map((feature, index) => (
                      <li key={index} className={styles.featureItem}>
                        <div className={styles.iconWrapper}>
                          {feature.icon}
                        </div>
                        {feature.title}: {feature.description}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>
            <div className={styles.contentRight}>
              <div className={styles.visualContent}>
                <div className={styles.svgContainer}>
                  <div className={styles.decorativeSvg}>
                    <div className={styles.visualElement}>
                      <Shield className={styles.visualIcon} />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className={styles.securityDisplay}>
            <div className={styles.securityContent}>
              <div className={styles.shieldContainer}>
                <Shield className={styles.shieldIconLarge} />
                <div className={styles.statusBadge}>
                  <div className={styles.statusDot}></div>
                </div>
              </div>
              <h2 className={styles.protectedTitle}>Fully Protected</h2>
              <p className={styles.protectedSubtitle}>
                Your campaigns are secured with our advanced fraud detection technology
              </p>
              <div className={styles.securityMetrics}>
                {securityMetrics.map((metric, index) => (
                  <div key={index} className={styles.metricCard}>
                    <div className={styles.metricIconWrapper}>{metric.icon}</div>
                    <h3 className={styles.metricTitle}>{metric.title}</h3>
                    <p className={styles.metricDescription}>{metric.description}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>

          <div className={styles.featuresSection}>
            <h2 className={styles.featuresTitle}>Advanced Fraud Detection Capabilities</h2>
            <div className={styles.featuresGrid}>
              {fraudDetectionFeatures.map((feature, index) => (
                <div key={index} className={styles.featureCard}>
                  <div className={styles.featureIconWrapper}>{feature.icon}</div>
                  <h3 className={styles.featureTitle}>{feature.title}</h3>
                  <p className={styles.featureDescription}>{feature.description}</p>
                </div>
              ))}
            </div>
          </div>

          <div className={styles.pricingSection}>
            <h2 className={styles.pricingTitle}>Fraud Detection Pricing</h2>
            <div className={styles.pricingCards}>
              <div className={styles.pricingCard}>
                <div className={styles.pricingHeader}>
                  <h3 className={styles.pricingName}>Basic</h3>
                  <div className={styles.pricingPrice}>$0.01</div>
                  <div className={styles.pricingDescription}>per install</div>
                </div>
                <ul className={styles.pricingFeatures}>
                  <li>Essential fraud detection</li>
                  <li>Basic IP reputation checks</li>
                  <li>Email support</li>
                </ul>
                <button 
                  className={styles.pricingButton} 
                  onClick={() => handleGetStarted('Basic')}
                >
                  Get Started
                </button>
              </div>
              
              <div className={styles.pricingCard}>
                <div className={styles.pricingHeader}>
                  <h3 className={styles.pricingName}>Professional</h3>
                  <div className={styles.pricingPrice}>$0.02</div>
                  <div className={styles.pricingDescription}>per install</div>
                </div>
                <ul className={styles.pricingFeatures}>
                  <li>Advanced fraud detection</li>
                  <li>Full IP reputation database</li>
                  <li>VPN/proxy detection</li>
                  <li>Real-time analytics</li>
                  <li>Priority support</li>
                </ul>
                <button 
                  className={styles.pricingButton} 
                  onClick={() => handleGetStarted('Professional')}
                >
                  Get Started
                </button>
              </div>
              
              <div className={styles.pricingCard}>
                <div className={styles.pricingHeader}>
                  <h3 className={styles.pricingName}>Enterprise</h3>
                  <div className={styles.pricingPrice}>Custom</div>
                  <div className={styles.pricingDescription}>tailored solutions</div>
                </div>
                <ul className={styles.pricingFeatures}>
                  <li>Premium fraud detection</li>
                  <li>Complete fraud prevention suite</li>
                  <li>Dedicated account manager</li>
                  <li>API access</li>
                  <li>24/7 phone support</li>
                </ul>
                <button 
                  className={styles.pricingButton} 
                  onClick={() => handleGetStarted('Enterprise')}
                >
                  Contact Sales
                </button>
              </div>
            </div>
          </div>

          <div className={styles.faqSection}>
            <h2 className={styles.faqTitle}>Frequently Asked Questions</h2>
            <div className={styles.faqList}>
              <div className={styles.faqItem}>
                <h3 className={styles.faqQuestion}>
                  <div className={styles.iconWrapper}>
                    <AlertTriangle className={styles.faqIcon} />
                  </div>
                  How does your fraud detection work?
                </h3>
                <p className={styles.faqAnswer}>
                  Our fraud detection system uses multiple layers of protection including IP reputation checks, 
                  device fingerprinting, behavioral analysis, and machine learning algorithms to identify and 
                  prevent fraudulent activity in real-time.
                </p>
              </div>
              <div className={styles.faqItem}>
                <h3 className={styles.faqQuestion}>
                  <div className={styles.iconWrapper}>
                    <AlertTriangle className={styles.faqIcon} />
                  </div>
                  Will fraud detection affect legitimate users?
                </h3>
                <p className={styles.faqAnswer}>
                  No, our system is designed to minimize false positives and only block clearly fraudulent traffic. 
                  Legitimate users will experience no disruption to their normal activities.
                </p>
              </div>
              <div className={styles.faqItem}>
                <h3 className={styles.faqQuestion}>
                  <div className={styles.iconWrapper}>
                    <AlertTriangle className={styles.faqIcon} />
                  </div>
                  How accurate is your fraud detection?
                </h3>
                <p className={styles.faqAnswer}>
                  Our system achieves 99.8% accuracy in identifying legitimate vs fraudulent traffic, with 
                  continuous improvements through machine learning and real-time updates to our detection algorithms.
                </p>
              </div>
              <div className={styles.faqItem}>
                <h3 className={styles.faqQuestion}>
                  <div className={styles.iconWrapper}>
                    <AlertTriangle className={styles.faqIcon} />
                  </div>
                  Can I customize fraud detection settings?
                </h3>
                <p className={styles.faqAnswer}>
                  Yes, our Professional and Enterprise plans offer customizable fraud detection settings, 
                  allowing you to adjust sensitivity levels and define specific rules based on your campaign needs.
                </p>
              </div>
            </div>
          </div>

          <div className={styles.ctaSection}>
            <h2 className={styles.ctaTitle}>Ready to Protect Your Campaigns?</h2>
            <p className={styles.ctaSubtitle}>
              Start using our advanced fraud detection technology to safeguard your investments today
            </p>
            <button 
              className={styles.ctaButton} 
              onClick={() => handleGetStarted('Custom')}
            >
              <Shield className={styles.ctaIcon} /> Activate Fraud Protection
            </button>
          </div>
        </div>
      </div>
      
      {/* Modal for getting started */}
      {isModalOpen && (
        <div className={styles.modalOverlay}>
          <div className={styles.modal}>
            <div className={styles.modalHeader}>
              <h2>Get Started with {selectedPlan} Fraud Detection</h2>
              <button className={styles.closeButton} onClick={handleCloseModal}>×</button>
            </div>
            <div className={styles.modalBody}>
              <form onSubmit={handleSubmit}>
                <div className={styles.formGroup}>
                  <label>Name:</label>
                  <input type="text" required />
                </div>
                <div className={styles.formGroup}>
                  <label>Email:</label>
                  <input type="email" required />
                </div>
                <div className={styles.formGroup}>
                  <label>Company:</label>
                  <input type="text" />
                </div>
                <div className={styles.formGroup}>
                  <label>Message:</label>
                  <textarea placeholder={`Interested in ${selectedPlan} fraud detection plan`} />
                </div>
                <button type="submit" className={styles.submitButton}>Submit</button>
              </form>
            </div>
          </div>
        </div>
      )}
      
    </div>
  );
};

export default FraudDetection;
