import React from "react";
import {
  Shield,
  Globe,
  Search,
  Bot,
  Fingerprint,
  TrendingUp,
  MousePointer,
  Monitor,
  Smartphone,
  BarChart,
  Clock,
  Target,
} from "lucide-react";
import styles from "./FraudDetection.module.css";

const FraudDetection = () => {
  const fraudDetectionFeatures = [
    {
      icon: <Globe className={styles.featureIcon} />,
      title: "IP Reputation Checks",
      description:
        "IP addresses are checked against global blacklists and databases to determine whether they have a negative reputation. This helps to prevent fraud and other malicious activities from suspicious IPs.",
    },
    {
      icon: <Search className={styles.featureIcon} />,
      title: "Proxy / VPN Detection",
      description:
        "Identifies if a user is masking their identity by using a proxy or VPN. This is important for preventing access from potentially fraudulent or compromised sources.",
    },
    {
      icon: <Bot className={styles.featureIcon} />,
      title: "Bot / Non-Human Detection",
      description:
        "Detects whether the traffic is generated by automated bots rather than real users. This helps in distinguishing genuine user actions from fraudulent activities.",
    },
    {
      icon: <Fingerprint className={styles.featureIcon} />,
      title: "Device Fingerprinting",
      description:
        "Collects unique information from a device's configuration, such as browser type, screen resolution, and hardware properties, to create a unique fingerprint.",
    },
    {
      icon: <TrendingUp className={styles.featureIcon} />,
      title: "Conversion Rate Analysis",
      description:
        "Monitors the percentage of users who take a desired action, such as completing a purchase or installing an app. Ensures conversion rates are within expected norms.",
    },
    {
      icon: <MousePointer className={styles.featureIcon} />,
      title: "Click-Through Rate Monitoring",
      description:
        "Evaluates the ratio of users who click on a specific link compared to total viewers. Helps understand the effectiveness of ads and content.",
    },
    {
      icon: <Monitor className={styles.featureIcon} />,
      title: "Platform Distribution Analysis",
      description:
        "Analyzes the distribution of users based on their platform or operating system. Helps identify unusual patterns in platform usage that may indicate fraud.",
    },
    {
      icon: <Smartphone className={styles.featureIcon} />,
      title: "Device Model Verification",
      description:
        "Monitors device types and specific models being used. Detects suspicious concentrations of certain devices which might indicate fraudulent behavior.",
    },
    {
      icon: <BarChart className={styles.featureIcon} />,
      title: "Incident Response Analytics",
      description:
        "Tracks the average time taken from when an issue is detected to when it's addressed. This metric helps evaluate response efficiency to security incidents.",
    },
    {
      icon: <Target className={styles.featureIcon} />,
      title: "Click-to-Install Analysis",
      description:
        "Measures the time it takes for a user to complete an installation after clicking. Extended times may indicate technical issues or fraudulent activity.",
    },
  ];

  return (
    <div className={styles.container}>
      <div className={styles.wrapper}>
        {/* Header Section */}
        <div className={styles.header}>
          <div className={styles.iconWrapper}>
            <Shield className={styles.shieldIcon} />
          </div>
          <h1 className={styles.mainTitle}>Advanced Fraud Detection System</h1>
          <p className={styles.subtitle}>
            Protect your business with our comprehensive, AI-powered fraud
            detection technology
          </p>
        </div>

        {/* Main Content Section */}
        <div className={styles.mainContent}>
          <div className={styles.contentLeft}>
            <h2 className={styles.sectionTitle}>Real Users, Real Results</h2>
            <p className={styles.description}>
              Our proprietary fraud detection system ensures the legitimacy and
              quality of all traffic and users. We provide real installs from
              genuine users and devices, giving you confidence in every
              conversion.
            </p>

            <div className={styles.benefitsCard}>
              <h3 className={styles.benefitsTitle}>Key Benefits</h3>
              <ul className={styles.benefitsList}>
                {[
                  "Real human traffic from verified users",
                  "Advanced fraud prevention algorithms",
                  "Pay only for genuine conversions",
                  "24/7 monitoring and protection",
                  "Transparent reporting and analytics",
                ].map((benefit, index) => (
                  <li key={index} className={styles.benefitItem}>
                    <div className={styles.bulletPoint}></div>
                    <span className={styles.benefitText}>{benefit}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div className={styles.guaranteeBox}>
              <p className={styles.guaranteeText}>
                💡 Rest assured - you're only charged for verified, genuine
                installs
              </p>
            </div>
          </div>

          {/* Animated Visual */}
          <div className={styles.visualSection}>
            <div className={styles.visualCard}>
              <div className={styles.securityDisplay}>
                <div className={styles.securityContent}>
                  <div className={styles.shieldContainer}>
                    <Shield className={styles.shieldIcon} />
                    <div className={styles.statusBadge}>
                      <div className={styles.statusDot}></div>
                    </div>
                  </div>
                  <h3 className={styles.protectedTitle}>Protected</h3>
                  <p className={styles.protectedSubtitle}>
                    Advanced Security Active
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Features Grid */}
        <div className={styles.featuresSection}>
          <h2 className={styles.featuresTitle}>
            Comprehensive Protection Features
          </h2>

          <div className={styles.featuresGrid}>
            {fraudDetectionFeatures.map((feature, index) => (
              <div key={index} className={styles.featureCard}>
                <div className={styles.featureIconWrapper}>{feature.icon}</div>
                <h3 className={styles.featureTitle}>{feature.title}</h3>
                <p className={styles.featureDescription}>
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* Call to Action */}
        <div className={styles.ctaSection}>
          <h2 className={styles.ctaTitle}>Ready to Secure Your Business?</h2>
          <p className={styles.ctaSubtitle}>
            Join thousands of businesses that trust our fraud detection system
          </p>
          <button className={styles.ctaButton}>Get Started Today</button>
        </div>
      </div>
    </div>
  );
};

export default FraudDetection;
